name: connect
version: 1.1.0.6

dependencies:
  - base
  - tidal
  - utils

library:
  exposed-modules: Connect
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - tidal
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.


tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - connect
      - hspec
